### PR TITLE
Create ArtnetNeoPixelRGBW.ino

### PR DESCRIPTION
**Pull request by DCandE**
Added example for SK6812RGBW leds tested with Arduino Ethernet and 2 meters of 60led/m strip using Openhab1 dmx binding.

### CODE REVIEW

**Comment by natcl** [comment]
Thanks !

**Comment by brendanrbercik** [comment]
Would this work with an Ardunio Yun, since it has the ethernet built in?

**Comment by natcl** [comment]
Never tried it with a Yun but if it uses the standard Arduino ethernet libs it should...

**Comment by DCandE** [comment]
There may be a way to merge the two examples. add a numEmiter const but I don't know yet how to logic the transmit for 3 or 4 channels
have a look at my branch and let me know what you think.

**Pull request merged**
